# Grafana datasource configuration for Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
      timeInterval: "15s"
      queryTimeout: "60s"
      httpHeaderName1: "X-Custom-Header"
      customQueryParameters: ""
      manageAlerts: true
      alertmanagerUid: ""
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: ""
          urlDisplayLabel: "View trace"
    secureJsonFields: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    basicAuth: false
    jsonData:
      maxLines: 1000
      timeout: "60s"
      derivedFields:
        - datasourceUid: "prometheus-uid"
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"